> # Necessary Imports

In [2]:
import pandas as pd
import logging
import os
import sys
sys.path.append('../')

from dotenv import load_dotenv
load_dotenv()

import sys
sys.path.append('../')

from scripts.scrapping import *
from scripts.setting import *
from scripts.cleaning import *

> # Telegram Access keys

In [3]:
api_id = os.getenv('TELEGRAM_API_ID')
api_hash = os.getenv('TELEGRAM_API_HASH')
phone = os.getenv('TELEGRAM_PHONE')

> # Logging

In [4]:
logging.basicConfig(filename='../logs/scraping.log', level=logging.INFO, 
                    format='%(asctime)s:%(levelname)s:%(message)s')

RAW_DATA_PATH = '../docs/raw/'
IMAGE_DATA_PATH = '../docs/images/'

> # Scrapping

In [5]:
import asyncio

async def main():
    await scrapping(logging, api_id, api_hash, RAW_DATA_PATH, IMAGE_DATA_PATH)

await main()

In [6]:
notebook_settings()

>> ## Scrapped Data

In [7]:
data = pd.read_csv('../docs/raw/all_scraped_messages.csv')
data[data['channel_name']=='CheMed123'].head()

channel_name  message_id                 date  \
10    CheMed123          97  2023-02-10 12:23:06   
11    CheMed123          96  2023-02-02 08:58:52   
12    CheMed123          95  2023-02-01 08:59:37   
13    CheMed123          94  2023-01-31 09:19:53   
14    CheMed123          93  2023-01-30 09:45:25   

                                                                                                                                                                                                                                                                                                                                              text  \
10  ⚠️**Notice!\n**Dear esteemed customers,\nDue to four-day motorbike movement restrictions, we have limited our services to matchmaking,drug information, and medical consultation only.\n\n**N.B. \n**🔅We will make deliveries for those for whom the medications are urgent.\n🔅You can book deliveries starting from Monday, February 13, 2023   
11                                                                                                                                                             Mela-One በውስጡ ሆርሞን ያለው ድንገተኛ ወሊድ መቆጣጠርያ ሲሆን ያለመከላከያ የተደረገ የግብረስጋ ግንኙነት ሲኖር በ72 ሰዓታት ወስጥ መወሰድ ይኖርበታል።\n\n📌ከChe-Med ለማዘዝ፡ \nበቴሌግራም ግሩፓችን- t.me/CheMeds\nዌብሳይት- www.chemeds.org\nይዘዙን።   
12                                                                                                           **አዚትሮማይሲን** በሃኪም መድሃኒት ማዘዣ ከሚታዘዙ አንቲባዮቲኮች አንዱ ሲሆን በርከት ያሉ ባክቴርያዎችን ይገላል።\n\nበቀን አንዴ ለ3 ቀናት ምግብ ከመብላታችን 1 ሰዓት ቀደም ብሎ ወይንም ከበላን ከ 2 ሰዓት በኋላ መወሰድ ይኖርበታል።\n\n📌የሃኪም ማዘዣ ካልዎት \nበቴሌግራም ግሩፓችን-t.me/CheMeds\nዌብሳይት- www.chemeds.org\nይላኩልን።   
13                                   **Che-Med Trivia #3\n\n**ምግብና መጠጦች አንዳንድ መድሃኒቶች በደንብ እንዳይሰሩ ሊያደርጉ ይችላሉ። በዚህ ሁኔታ እነዚህን መድሃኒቶች ምግብ ከወሰድን ከ1 ሰዓት እስከ 2 ሰዓት ባለ ጊዜ ውስጥ መውሰድ ያስፈልግዎታል።\n\nከነዚህም ወስጥ **የእንቅርት መድሃኒቶች፣Omeprazole፣Sildenafil(Viagra)፣Captopril እና Ampicillin** ይጠቀሳሉ።\n\nመድሃኒትዎ ከምግብ ጋር ያለውን አወሳሰድ እርግጠኛ ካልሆኑ ሃኪምዎን ወይም ፋርማሲስትዎን ያማክሩ።   
14                                                                          **Che-Med Trivia #2\n\n**እንደ Ciprofloxacin, Doxycycline, Levothyroxine, Iron supplement ያሉ መድሃኒቶችን ከወተት እና ከወተት ተዋፅዖዎች ጋር እንዲሁም ከእንቁላል ጋር መውሰድ መድሃኒቶቹ በሰውነታችን የሚፈለገውን ስራ እንዳይሰሩ ያደርጋቸዋል።\n\nይህም በወተት ተዋጽኦዎች ውስጥ ያለው ካልሲየም እነዚህ መድሃኒቶች በሰውታችን ወስጥ እንዳይዋህዱ ጣልቃ ስለሚገባ ነው።   

                                          image_path  
10      ../docs/images/photo_2024-10-16_09-49-52.jpg  
11  ../docs/images/photo_2024-10-16_09-49-52 (1).jpg  
12      ../docs/images/photo_2024-10-16_09-49-53.jpg  
13  ../docs/images/photo_2024-10-16_09-49-53 (1).jpg  
14  ../docs/images/photo_2024-10-16_09-49-53 (2).jpg

> # Cleaning the Data

In [8]:
cleaning(data)

/home/aman/Documents/10Academy/week7/notebooks/../scripts/cleaning.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['text'].fillna('No text', inplace=True)
/home/aman/Documents/10Academy/week7/notebooks/../scripts/cleaning.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.


>> ## Cleaned Data

In [9]:
cleaned_data = pd.read_csv('../docs/cleaned/all_scraped_messages_cleaned.csv')
cleaned_data.head()

channel_name  message_id                 date  \
0    DoctorsET         864  2023-12-18 17:04:02   
1    DoctorsET         863  2023-11-03 16:14:39   
2    DoctorsET         862  2023-10-02 16:37:39   
3    DoctorsET         861  2023-09-16 07:54:32   
4    DoctorsET         860  2023-09-01 16:16:15   

                                                                                                                                                                                                                                                                                                                                       text  \
0  https://youtu.be/5DBoEm-8kmA?si=LDLuEecNfULJVDzL   👈👈\n\nበቀን አንዴ ብቻ የሚባለው የቢዝነስ አማካሪ \n\nበ 10,000 ብር ብቻ የተጀመረ ቢዝነስ እስከ ሚሊየኖች ያየገው የፕራግማ ኢንቨስትመንት መስራች መርድ ብስራት \n\nብላክ ማርኬት ዋጋ ማነው ሚተምነው ?\n\nኢትዮጵያ ውስጥ ቢዝነስ ለመጀመር ጥሩ ሰአት ነው ወይ ??\n\n3 ቢዝነስ ስንጀምር የምንሰራው ስህተቶች !\n\nአሁኑኑ ይመልከተቱ  👇👇\n\nhttps://youtu.be/5DBoEm-8kmA?si=LDLuEecNfULJVDzL   
1         ዶክተርስ ኢትዮጵያ በ አዲስ አቀራረብ በ ቴሌቪዥን ፕሮግራሙን ለመጀመር ከፋተኛ ዝግጅት በማድረግ ላይ ይገኛል ።\n\nዩሃንስ ግርማ ጆኒ ( በ ቲክቶክ ከ 500,000) በላይ ተከታይ ያገኘው ከ አሜሪካ ወደ ኢትዮጵያ \nገንዳ ውስጥ ከመተኛት እስከ ከፋተኛ ተከፋይ በኢትዮጵያ ( 1 take production ) በመባል የሚታወቀው ዩሃንስ ግርማ ( ጆኒ) \n\nከዲፕሬሽን እስከ ታዋቂነትን ያተረፈው ጆኒ \n\nአሁኑኑ ይመልከቱ 👇\n\nhttps://youtu.be/gwVN5eJQpko?si=xARsSxIEdZtE91GY   
2                                                                              ሞት በስኳር \n\nለልጆቻችን የምናሲዘው ምሳቃ ሳናቀው እድሚያቸውን ይቀንሰው ይሆን \n\nየታሸገ ትክክለኛ ጁስ ኢትዮጵያ ውስጥ የለም...!\n\nሁሉም ወላጅ ሊያየው የሚገባ\n\nየታሸጉ ጁሶች መጠጣት እራስን ለከፍተኛ ጉዳት እስከ ሞት ድረስ ማጋለጥ ነው !\n\nለሁሉም ኢኮኖሚ ጤናንም የሚጠብቅ አመጋገብ የቱ ነው??\n\nhttps://youtu.be/oHiSRrNF7I0?si=Absgm414YSt_kjNq   
3                                                                                                                                                                                                   ከ HIV የተፈወሰ ሰው አጋጥሟችሁ ያቃል ? ፈውስ እና ህክምና ?\n\nሙሉ ቪዲዮውን ተመልክተው ሃሳብ አስተያየቶን ያካፍሉን 👇👇👇👇\n\nhttps://youtu.be/tTeErZxIh_Q?si=jKHyfWcC3sfXbC8L   
4   በቅርብ ጊዜ በሃገራችን ላይ እየተስተዋለ ያለ የተመሳሳይ ፆታ ( Homosexuality ) ግብረ ሰዶም በተለያዩ ቦታዎች ላይ እየታየ ይገኛል\n\nይህም አጥብቀን ምንቃወመው ጉዳይ ሲሆን \n\n- ይህ ችግር በህምና ይለያል ወይ ?\n- ቅድመ ምልክት አለው ወይ ?\n\nወላጆች ልጆቻችሁን እንዴት መጠበቅ ትችላለቹ ህክምናስ አለው ወይ ??\n\nበምንመገበው ምግብ ሊቀይሩየን ይችላሉ ወይ ? \n\nአሁኑኑ ገብተው ሙሉ ቪዲዮውን ይመልከቱ !\n\nhttps://youtu.be/0k65P5ouw7s?si=qaUgo75bUa3AMQxD   

  image_path  
0   No image  
1   No image  
2   No image  
3   No image  
4   No image

>> ## Store Cleaned Data

In [10]:
def store_cleaned_data(data, channel_name):
    cleaned_file_path = os.path.join(RAW_DATA_PATH, f'cleaned_{channel_name}.csv')
    data.to_csv(cleaned_file_path, index=False)
    logging.info(f'Stored cleaned data to {cleaned_file_path}')


In [11]:
import torch
import os
import cv2
import pandas as pd
import logging

# Setup logging
logging.basicConfig(filename='../logs/yolo_detection.log', level=logging.INFO,
                    format='%(asctime)s:%(levelname)s:%(message)s')

# Load YOLO model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Define paths
IMAGE_DIR = '../docs/images/'
OUTPUT_DIR = '../docs/yolo_output/'

# Create output directory if it doesn't exist
os.makedirs(OUTPUT_DIR, exist_ok=True)

# List to store all detection results
all_detections = []

# Loop through all images in the directory
for img_file in os.listdir(IMAGE_DIR):
    img_path = os.path.join(IMAGE_DIR, img_file)
    
    if img_file.endswith(('.jpg', '.jpeg', '.png')):
        # Read the image using OpenCV
        img = cv2.imread(img_path)
        height, width, _ = img.shape  # Get image dimensions
        
        # Run YOLO detection
        results = model(img)
        
        # Convert results to pandas DataFrame for easier manipulation
        results_df = results.pandas().xyxy[0]  # Get results in YOLO xyxy format
        
        # Add image metadata to each detection
        results_df['image_file'] = img_file
        results_df['image_width'] = width
        results_df['image_height'] = height
        results_df['aspect_ratio'] = width / height
        
        # Append results to the list
        all_detections.append(results_df)
        
        # Save the detection results to the output folder
        results.save(OUTPUT_DIR)
        
        logging.info(f'Processed {img_file} and saved results to {OUTPUT_DIR}')
        print(f'Detected objects in {img_file}')

# Concatenate all detection results into a single DataFrame
if all_detections:
    final_detections_df = pd.concat(all_detections, ignore_index=True)

    # Save the final DataFrame to CSV
    final_detections_df.to_csv(os.path.join(OUTPUT_DIR, 'yolo_detections.csv'), index=False)

    # Preview the DataFrame
    final_detections_df.head()
else:
    print("No valid detections found.")


Using cache found in /home/aman/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2024-10-15 Python-3.10.12 torch-2.4.1+cu121 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape... 
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2365
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2366
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(a

Detected objects in photo_2024-10-16_09-49-54 (1).jpg
Detected objects in photo_2024-10-16_09-49-58.jpg


Saved 1 image to runs/detect/exp2367
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2368
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Detected objects in photo_2024-10-16_09-49-57.jpg
Detected objects in photo_2024-10-16_09-49-58 (1).jpg


Saved 1 image to runs/detect/exp2369
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2370
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Detected objects in photo_2024-10-16_09-49-52.jpg
Detected objects in photo_2024-10-16_09-49-53 (2).jpg


Saved 1 image to runs/detect/exp2371
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2372
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Detected objects in photo_2024-10-16_09-49-57 (1).jpg
Detected objects in photo_2024-10-16_09-49-53 (1).jpg


Saved 1 image to runs/detect/exp2373
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2374
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Detected objects in photo_2024-10-16_09-49-58 (3).jpg
Detected objects in photo_2024-10-16_09-49-54.jpg


Saved 1 image to runs/detect/exp2375
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2376
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Detected objects in photo_2024-10-16_09-49-52 (1).jpg
Detected objects in photo_2024-10-16_09-49-54 (2).jpg


Saved 1 image to runs/detect/exp2377
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2378
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Detected objects in photo_2024-10-16_09-49-53.jpg
Detected objects in photo_2024-10-16_09-49-58 (2).jpg


Saved 1 image to runs/detect/exp2379
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2380


Detected objects in photo_2024-10-16_09-49-56 (1).jpg
Detected objects in photo_2024-10-16_09-49-56.jpg


/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2381
/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2382


Detected objects in photo_2024-10-16_09-49-53 (3).jpg
Detected objects in photo_2024-10-16_09-49-55.jpg


/home/aman/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:892: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
Saved 1 image to runs/detect/exp2383


Detected objects in photo_2024-10-16_09-49-59.jpg


/tmp/ipykernel_22328/3707946373.py:56: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_detections_df = pd.concat(all_detections, ignore_index=True)


xmin        ymin         xmax         ymax  confidence  ...  \
0  811.167236  574.372620   986.870728   921.034851    0.300178  ...   
1   17.502714  270.205658   596.414551  1077.265137    0.870186  ...   
2  726.834900    7.953853  1076.723145   427.751190    0.408299  ...   
3  442.037567  625.851074   577.163391   763.936462    0.354230  ...   
4  237.321747  583.221985   734.137146   965.405457    0.672652  ...   

          name                         image_file image_width  image_height  \
0          cup  photo_2024-10-16_09-49-58 (1).jpg        1280          1280   
1       person  photo_2024-10-16_09-49-53 (2).jpg        1080          1080   
2        zebra  photo_2024-10-16_09-49-53 (2).jpg        1080          1080   
3  sports ball  photo_2024-10-16_09-49-53 (2).jpg        1080          1080   
4         bowl  photo_2024-10-16_09-49-57 (1).jpg        1000          1000   

   aspect_ratio  
0           1.0  
1           1.0  
2           1.0  
3           1.0  
4           1.0  

[5 rows x 11 columns]

In [12]:
print(model.names)

{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microw

In [13]:
import cv2
import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

# Define paths
IMAGE_DIR = '../docs/images/'
OUTPUT_DIR = '../docs/yolo_output/'

# Create output directory if it doesn't exist
os.makedirs(OUTPUT_DIR, exist_ok=True)

# List to store all detection results
all_detections = []

# Function to display an image with bounding boxes in Jupyter Notebook
def display_image_with_boxes(img, boxes):
    fig, ax = plt.subplots(1)
    ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))  # Display image
    
    # Draw bounding boxes
    for box in boxes:
        x, y, w, h = box
        rect = Rectangle((x, y), w, h, linewidth=2, edgecolor='r', facecolor='none')
        ax.add_patch(rect)
    
    plt.show()

# Loop through all images in the directory
for img_file in os.listdir(IMAGE_DIR):
    img_path = os.path.join(IMAGE_DIR, img_file)
    
    if img_file.endswith(('.jpg', '.jpeg', '.png')):
        # Read the image using OpenCV
        img = cv2.imread(img_path)
        height, width, _ = img.shape  # Get image dimensions
        
        # Select ROIs
        boxes = cv2.selectROIs("Select ROIs", img)
        cv2.destroyWindow("Select ROIs")
        
        if len(boxes) > 0:
            display_image_with_boxes(img, boxes)  # Show image with selected boxes
            
            # Collect labels for each bounding box
            for i, box in enumerate(boxes):
                x, y, w, h = box
                label = input(f"Enter label for section {i+1} of {img_file}: ")
                
                detection = {
                    'image_file': img_file,
                    'label': label,
                    'bbox_x_min': x,
                    'bbox_y_min': y,
                    'bbox_width': w,
                    'bbox_height': h,
                    'image_width': width,
                    'image_height': height
                }
                all_detections.append(detection)
            
            output_image_path = os.path.join(OUTPUT_DIR, img_file)
            for box in boxes:
                x, y, w, h = box
                cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
            cv2.imwrite(output_image_path, img)

if all_detections:
    final_detections_df = pd.DataFrame(all_detections)

    final_detections_df.to_csv(os.path.join(OUTPUT_DIR, 'custom_labeled_data.csv'), index=False)

    final_detections_df.head()
else:
    print("No detections made.")


Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 254, 254],
        [255, 254, 240],
        [255, 255, 240]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 245],
        [255, 255, 241],
        [255, 254, 243]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 218],
        [255, 255, 248],
        [255, 251, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 254, 254],
        [255, 254, 240],
        [255, 255, 240]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 245],
        [255, 255, 241],
        [255, 254, 243]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 218],
        [255, 255, 248],
        [255, 251, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 254, 254],
        [255, 254, 240],
        [255, 255, 240]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 245],
        [255, 255, 241],
        [255, 254, 243]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 218],
        [255, 255, 248],
        [255, 251, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 254, 254],
        [255, 254, 240],
        [255, 255, 240]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 245],
        [255, 255, 241],
        [255, 254, 243]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 218],
        [255, 255, 248],
        [255, 251, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 254, 254],
        [255, 254, 240],
        [255, 255, 240]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 245],
        [255, 255, 241],
        [255, 254, 243]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 218],
        [255, 255, 248],
        [255, 251, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [199, 195, 184],
        [121, 112, 102],
        [ 53,  45,  32]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 254, 249],
        [231, 228, 220],
        [203, 201, 191]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [251, 255, 255],
        [251, 255, 255],
        [251, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[245, 243, 209],
        [245, 243, 209],
        [245, 243, 208],
        ...,
        [245, 243, 235],
        [245, 243, 235],
        [245, 243, 235]],

       [[245, 243, 209],
        [245, 243, 209],
        [245, 243, 208],
        ...,
        [245, 243, 235],
        [245, 243, 235],
        [245, 243, 235]],

       [[245, 243, 208],
        [245, 243, 208],
        [245, 243, 208],
        ...,
        [245, 243, 235],
        [245, 243, 235],
        [245, 243, 235]],

       ...,

       [[249, 248, 227],
        [249, 248, 227],
        [249, 248, 227],
        ...,
        [255, 255, 254],
        [255, 255, 254],
        [255, 255, 254]],

       [[249, 248, 227],
        [249, 248, 227],
        [249, 248, 227],
        ...,
        [255, 255, 254],
        [255, 255, 254],
        [255, 255, 254]],

       [[249, 248, 227],
        [249, 248, 227],
        [249, 248, 227],
        ...,
        [255, 255, 254],
        [255, 255, 254],
        [255, 255, 254]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[157, 165,  11],
        [157, 165,  11],
        [157, 165,  11],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[157, 165,  11],
        [157, 165,  11],
        [157, 165,  11],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[157, 165,  11],
        [157, 165,  11],
        [157, 165,  11],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       ...,

       [[237, 228, 224],
        [237, 228, 224],
        [237, 228, 224],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[237, 228, 224],
        [237, 228, 224],
        [237, 228, 224],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[237, 228, 224],
        [237, 228, 224],
        [237, 228, 224],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[245, 243, 209],
        [245, 243, 209],
        [245, 243, 208],
        ...,
        [245, 243, 235],
        [245, 243, 235],
        [245, 243, 235]],

       [[245, 243, 209],
        [245, 243, 209],
        [245, 243, 208],
        ...,
        [245, 243, 235],
        [245, 243, 235],
        [245, 243, 235]],

       [[245, 243, 208],
        [245, 243, 208],
        [245, 243, 208],
        ...,
        [245, 243, 235],
        [245, 243, 235],
        [245, 243, 235]],

       ...,

       [[249, 248, 227],
        [249, 248, 227],
        [249, 248, 227],
        ...,
        [255, 255, 254],
        [255, 255, 254],
        [255, 255, 254]],

       [[249, 248, 227],
        [249, 248, 227],
        [249, 248, 227],
        ...,
        [255, 255, 254],
        [255, 255, 254],
        [255, 255, 254]],

       [[249, 248, 227],
        [249, 248, 227],
        [249, 248, 227],
        ...,
        [255, 255, 254],
        [255, 255, 254],
        [255, 255, 254]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[ 66, 185, 241],
        [ 66, 185, 241],
        [ 66, 185, 241],
        ...,
        [108, 187, 228],
        [124, 187, 225],
        [130, 188, 223]],

       [[ 66, 185, 241],
        [ 66, 185, 241],
        [ 66, 185, 241],
        ...,
        [ 87, 182, 238],
        [ 91, 183, 236],
        [ 93, 184, 235]],

       [[ 66, 185, 241],
        [ 66, 185, 241],
        [ 66, 185, 241],
        ...,
        [ 75, 180, 243],
        [ 75, 180, 243],
        [ 75, 181, 242]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 66,  42,  12],
        [ 66,  42,  12],
        [ 66,  42,  12]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 66,  42,  12],
        [ 66,  42,  12],
        [ 66,  42,  12]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 66,  42,  12],
        [ 66,  42,  12],
        [ 66,  42,  12]],

       ...,

       [[157, 165,  11],
        [157, 165,  11],
        [157, 165,  11],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[157, 165,  11],
        [157, 165,  11],
        [157, 165,  11],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]],

       [[157, 165,  11],
        [157, 165,  11],
        [157, 165,  11],
        ...,
        [157, 165,  11],
        [157, 165,  11],
        [157, 165,  11]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       ...,

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

Finish the selection process by pressing ESC button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

True

image_file            label  bbox_x_min  bbox_y_min  \
0  photo_2024-10-16_09-49-54 (1).jpg  medicine bottle          38          67   
1  photo_2024-10-16_09-49-54 (1).jpg         medicine          45         392   
2  photo_2024-10-16_09-49-54 (1).jpg             logo         757         186   
3  photo_2024-10-16_09-49-54 (1).jpg  medicine bottle         757         186   
4  photo_2024-10-16_09-49-54 (1).jpg  medicine bottle          76          71   

   bbox_width  bbox_height  image_width  image_height  
0         635          625         1080          1080  
1         631          290         1080          1080  
2         186          155         1080          1080  
3         186          155         1080          1080  
4         594          620         1080          1080

In [18]:
import pandas as pd
import os

# Load your CSV
csv_path = '../docs/yolo_output/custom_labeled_data.csv'
df = pd.read_csv(csv_path)

# Define a path for YOLO annotation files
yolo_output_dir = '../docs/yolo_annotations/'
os.makedirs(yolo_output_dir, exist_ok=True)

# Convert each row to YOLO format
for _, row in df.iterrows():
    # YOLO format: class_id x_center y_center width height (normalized)
    class_id = 0  # Modify if you have multiple classes
    x_center = (row['bbox_x_min'] + row['bbox_width'] / 2) / row['image_width']
    y_center = (row['bbox_y_min'] + row['bbox_height'] / 2) / row['image_height']
    width = row['bbox_width'] / row['image_width']
    height = row['bbox_height'] / row['image_height']

    # Save to YOLO format text file
    annotation_filename = os.path.splitext(row['image_file'])[0] + '.txt'
    with open(os.path.join(yolo_output_dir, annotation_filename), 'w') as f:
        f.write(f"{class_id} {x_center} {y_center} {width} {height}\n")


80

80

80

80

64

78

81

23

42

81

81

28

79

22

68

77

68

82

56

79

77

80

79

In [20]:
!python ../yolov5/train.py --img 640 --batch 16 --epochs 50 --data data.yaml --weights yolov5s.pt

2024-10-16 10:43:34.597651: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-16 10:43:35.029724: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-16 10:43:35.078316: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
train: weights=yolov5s.pt, cfg=, data=data.yaml, hyp=../yolov5/data/hyps/hyp.scratch-low.yaml, epochs=50, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, evolve_population=../yolov5/data/hyps, resume_evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, sin

In [23]:
import pandas as pd

df_detections = pd.read_csv('../docs/yolo_output/custom_labeled_data.csv')

df_detections.head()


image_file            label  bbox_x_min  bbox_y_min  \
0  photo_2024-10-16_09-49-54 (1).jpg  medicine bottle          38          67   
1  photo_2024-10-16_09-49-54 (1).jpg         medicine          45         392   
2  photo_2024-10-16_09-49-54 (1).jpg             logo         757         186   
3  photo_2024-10-16_09-49-54 (1).jpg  medicine bottle         757         186   
4  photo_2024-10-16_09-49-54 (1).jpg  medicine bottle          76          71   

   bbox_width  bbox_height  image_width  image_height  
0         635          625         1080          1080  
1         631          290         1080          1080  
2         186          155         1080          1080  
3         186          155         1080          1080  
4         594          620         1080          1080

In [35]:
import pandas as pd
import logging
import psycopg2

# Setup logging
logging.basicConfig(filename='../logs/csv_to_db.log', level=logging.INFO,
                    format='%(asctime)s:%(levelname)s:%(message)s')

def insert_data(csv_file_path):
    # Connect to PostgreSQL
    conn = psycopg2.connect(
        dbname="tenacad",
        user="postgres",
        password="admin",
        host="localhost",
        port="5432"
    )
    cursor = conn.cursor()

    insert_query = """
        INSERT INTO custom_yolo_detections (
            image_file, label, bbox_x_min, bbox_y_min, bbox_width, bbox_height, image_width, image_height
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    """

    try:
        detections_df = pd.read_csv(csv_file_path)
        
        logging.info(f'Read CSV with columns: {detections_df.columns.tolist()}')

        for _, row in detections_df.iterrows():
            cursor.execute(insert_query, (
                row['image_file'], row['label'], row['xmin'],  
                row['ymin'], row['width'], row['height'], 
                row['image_width'], row['image_height']
            ))
            logging.info(f'Inserted row: {row.to_dict()}')

        conn.commit()
        logging.info(f'Successfully inserted {len(detections_df)} records into the database.')

    except Exception as e:
        logging.error(f'Error occurred: {e}')

    finally:
        cursor.close()
        conn.close()

# Call the function to insert data
insert_data('../docs/yolo_output/custom_labeled_data.csv')
